# Generated by Django 5.0.14 on 2026-09-16 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Random token used in order URLs so one customer can't view another's order by guessing IDs", unique=True)),
                ('email', models.EmailField(help_text='Required by Paystack for online payments, and useful for receipts', max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'Pay online now (card / bank transfer / USSD)'), ('delivery', 'Pay on delivery / pickup')], default='delivery', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('accessory', 'Accessory'), ('gaming', 'Gaming')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('uk', 'UK-Used'), ('ng', 'Nigerian-Used')], default='new', max_length=10)),
                ('spec', models.CharField(blank=True, help_text="Short spec line, e.g. '128GB · Blue · Battery 89%'", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Naira', max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional original price. If higher than price, a discount badge shows automatically.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='The real number of units you have. This is the source of truth — the badge below is set automatically from this number.')),
                ('stock_status', models.CharField(choices=[('ok', 'In stock'), ('warn', 'Low stock'), ('low', 'Last unit'), ('out', 'Out of stock')], default='out', editable=False, help_text='Set automatically from the quantity above — not editable directly.', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Product photo. If left empty, the emoji below is shown instead.', null=True, upload_to='products/')),
                ('emoji', models.CharField(default='📱', help_text='Fallback thumbnail when no photo is uploaded', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this product from the shop')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the homepage Featured row')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Show in the homepage Best Sellers row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('price_range', models.CharField(help_text="e.g. '₦25,000 – ₦120,000'", max_length=100)),
                ('time_estimate', models.CharField(help_text="e.g. '2–4 hrs'", max_length=100)),
                ('icon', models.CharField(default='🔧', help_text='Emoji shown on the repair card', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_location', models.CharField(blank=True, help_text="e.g. 'Makurdi, Benue'", max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='RepairBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Random token used in confirmation URLs so booking pages can't be guessed by ticket number alone", unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=30)),
                ('device', models.CharField(max_length=150)),
                ('issue_description', models.TextField(blank=True)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.repairtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('verified_purchase', models.BooleanField(default=False, help_text="Tick only if you've confirmed this customer actually bought the item")),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews are shown publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
